//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishBattle.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnglishBattleEntities : DbContext
    {
        public EnglishBattleEntities()
            : base("name=EnglishBattleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Joueur> Joueurs { get; set; }
        public virtual DbSet<Partie> Parties { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Verbe> Verbes { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
    }
}
